# Site settings
title: Tableau Extensions API
email: github@tableau.com
description: Create add-ins to extend the functionality of Tableau.
baseurl: "/ProjectFrelard"
permalinks: pretty
defaults:
  -
    scope:
      path: "" # Apply to all files
    values:
      layout: "default"

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude
exclude: ['node_modules']